In [1]:
import numpy as np
from pandas.plotting import scatter_matrix
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
data = files.upload()
import io
df = pd.read_csv(io.BytesIO(data['Power2.csv']))

Saving Power2.csv to Power2.csv


In [2]:
cancer=df


In [3]:
cancer.head()

Diagnosis  F1 = 1.896 Hz  ...  F4 = 0 Hz  F6 = 0.237 Hz
0          1      -33.96365  ...    2.12946      -17.05243
1          1      -36.48426  ...    1.54439      -21.00131
2          1      -36.48426  ...    1.54439      -21.00131
3          1      -30.58541  ...    3.43557      -13.57998
4          1      -33.53178  ...    2.43515      -16.24663

[5 rows x 6 columns]

In [4]:
df.describe()

Diagnosis  F1 = 1.896 Hz  ...   F4 = 0 Hz  F6 = 0.237 Hz
count  110.000000     110.000000  ...  110.000000     110.000000
mean     0.681818     -28.497822  ...    3.622631     -13.768993
std      0.467902       6.519169  ...    2.124332       5.899030
min      0.000000     -42.403020  ...    0.864500     -27.408780
25%      0.000000     -33.152955  ...    2.219682     -17.603262
50%      1.000000     -28.267530  ...    3.233405     -12.819150
75%      1.000000     -22.930238  ...    4.286910     -10.212028
max      1.000000     -15.633210  ...   13.784220      -1.058800

[8 rows x 6 columns]

In [5]:
X=cancer['F6 = 0.237 Hz']
y=cancer['Diagnosis']


In [6]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y)
Xtrain
#Xtest
#ytrain
#ytest

36    -7.68535
97   -23.37566
8    -11.27166
13   -21.02503
98   -22.75252
        ...   
78   -10.14298
16   -23.36729
66   -17.48966
24   -14.53733
34   -11.66216
Name: F6 = 0.237 Hz, Length: 82, dtype: float64

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler

StandardScaler()

In [8]:
scaler.fit(Xtest.values.reshape(-1,1))

StandardScaler()

In [9]:
Xtrain=scaler.transform(Xtrain.values.reshape(-1,1))
Xtrain

array([[ 1.1308948 ],
       [-1.60382383],
       [ 0.50582437],
       [-1.19412436],
       [-1.49521459],
       [ 0.58749481],
       [-0.36565868],
       [ 0.40058772],
       [ 0.65898999],
       [ 2.25062405],
       [-0.68087714],
       [-0.60433268],
       [ 0.30013542],
       [ 1.11548203],
       [ 0.09199066],
       [ 0.32409205],
       [ 0.47224325],
       [ 1.46791214],
       [ 0.30830106],
       [ 0.4206733 ],
       [ 0.58387996],
       [ 0.86609944],
       [ 0.77839322],
       [ 0.06661353],
       [-0.54788251],
       [-1.56745575],
       [ 2.28585921],
       [-0.31150396],
       [-0.57793245],
       [-1.18999012],
       [ 0.28644641],
       [ 1.42438584],
       [ 1.24712414],
       [-0.36128043],
       [ 0.46987809],
       [ 0.40659561],
       [ 0.50313851],
       [ 1.59485008],
       [-1.58229336],
       [-1.32679133],
       [ 1.27258842],
       [ 0.08689955],
       [ 1.17351827],
       [ 0.17421884],
       [-0.93589464],
       [-0

In [10]:
Xtest=scaler.transform(Xtest.values.reshape(-1,1))
Xtest

array([[-0.78411988],
       [ 0.77896316],
       [-1.56703745],
       [-0.66065387],
       [-0.9450555 ],
       [ 1.3590833 ],
       [ 0.93153618],
       [ 1.50718569],
       [-0.14721493],
       [-0.06453882],
       [ 0.60267751],
       [-0.09675174],
       [-2.07710904],
       [-0.13908414],
       [ 1.42517713],
       [ 0.10349926],
       [-0.21945957],
       [-1.81678082],
       [-0.31956154],
       [ 0.18576752],
       [-1.18999012],
       [ 0.32006065],
       [ 0.46256647],
       [ 0.4399397 ],
       [ 0.38367428],
       [-0.77345312],
       [ 0.04825172],
       [ 2.25242798]])

In [11]:
ytrain= scaler.transform(ytrain.values.reshape(-1,1))
ytrain

array([[2.64469462],
       [2.47040114],
       [2.64469462],
       [2.47040114],
       [2.47040114],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.47040114],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.644

In [12]:
ytest=scaler.transform(ytest.values.reshape(-1,1))
ytest

array([[2.47040114],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114],
       [2.64469462],
       [2.64469462],
       [2.64469462],
       [2.47040114]])

In [13]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.50)

In [29]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(30,30,30), alpha=0.001, learning_rate_init=0.1 )


In [30]:
mlp.fit(Xtrain.values.reshape(-1,1),ytrain.values.reshape(-1,1))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(alpha=0.001, hidden_layer_sizes=(30, 30, 30),
              learning_rate_init=0.1)

In [31]:
predictions=mlp.predict(Xtest.values.reshape(-1,1))

In [32]:
from sklearn.metrics import classification_report,confusion_matrix

In [33]:
print(confusion_matrix(ytest,predictions))

[[ 0 18]
 [ 0 37]]


In [34]:
print(classification_report(ytest,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        18
           1       0.67      1.00      0.80        37

    accuracy                           0.67        55
   macro avg       0.34      0.50      0.40        55
weighted avg       0.45      0.67      0.54        55



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
from sklearn.model_selection import learning_curve #learningcurves

In [28]:
train_sizes, train_scores, valid_scores = learning_curve(
...     mlp, X, y, train_sizes=(76,), cv=10)

In [ ]:
from sklearn.model_selection import ShuffleSplit

In [ ]:
train_sizes, train_scores, test_scores = learning_curve(
...     mlp, X, y, # Number of folds in cross-validation
                                                        cv=10,
                                                        # Evaluation metric
                                                        scoring='accuracy',
                                                        # Use all computer cores
                                                        n_jobs=-1, 
                                                        # 50 different sizes of the training set
                                                        train_sizes=np.linspace(0.01, 1.0, 50))

In [ ]:
train_mean = np.mean(train_scores, axis=1)# Create means and standard deviations of training set scores
train_std = np.std(train_scores, axis=1)

In [ ]:
test_mean = np.mean(test_scores, axis=1) # Create means and standard deviations of test set scores
test_std = np.std(test_scores, axis=1)

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator = mlp, X= Xtrain.values.reshape(-1,1), y= ytrain.values.reshape(-1,1), cv=10)
print("Accuracy:{:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation:{:.2f}%".format(accuracies.std()*100))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iteratio

Accuracy:61.33%
Standard Deviation:11.85%


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
